version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - ./.env
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - '8888:80'
    env_file:
      - ./.env
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=${DATABASE_URL}
    container_name: backend
    restart: always
    depends_on:
      - postgres
    env_file:
      - ./.env
    ports:
      - 5000:5000

  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    depends_on:
      - pgadmin
      - backend
    environment:
      - BASE_URL=$BASE_URL
    ports:
      - 80:80
      - 443:443
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  local_pgdata:
  pgadmin-data:
  caddy_data:
  caddy_config:

networks:
  default:
    name: server-network
